<?php
define('VISITEUR',1); // If the user is visitor (not registered)
define('INSCRIT',2); // If the user is registered
define('MODO',3); // If the user is moderator
define('ADMIN',4); // If the user is administrator

// Custom Error Messages:
// You are already connected
define('ERR_IS_CO','<div class="ui main container animated fadeIn"><div class="ui raised clearing segments"><div class="ui center aligned segment"><h1 class="ui center aligned icon header"><i class="circular warning sign orange icon"></i><div class="content">You are already connected<div class="sub header"><a href="./deconnexion.php">Log out</a> if you want to access this page.</div></div></h1></div><div class="ui '.$config['forum_color'].' padded segment"><div class="ui icon warning message"><i class="meh icon"></i><div class="content"><div class="header">Oops...</div><p>You can not access this page.</p></div></div>');
// You are not connected
define('ERR_IS_NOT_CO','<div class="ui main container animated fadeIn"><div class="ui raised clearing segments"><div class="ui center aligned segment"><h1 class="ui center aligned icon header"><i class="circular warning sign orange icon"></i><div class="content">You are not connected<div class="sub header"><a href="./connexion.php">Log in</a> if you want to access this page.</div></div></h1></div><div class="ui '.$config['forum_color'].' padded segment"><div class="ui icon warning message"><i class="meh icon"></i><div class="content"><div class="header">Oops...</div><p>You can not access this page.</p></div></div>');
// You must have an authorization
define('ERR_AUTH_VIEW','<div class="ui main container animated fadeIn"><div class="ui raised clearing segments"><div class="ui center aligned segment"><h1 class="ui center aligned icon header"><i class="circular remove red icon"></i><div class="content">Insufficient authorization</div></h1></div><div class="ui '.$config['forum_color'].' padded segment"><div class="ui icon warning message"><i class="meh icon"></i><div class="content"><div class="header">Oops...</div><p>You do not have <strong>permission</strong> to access this page.</p></div></div>');
// Lorem...
define('ERR_AUTH_VERR','<div class="ui raised clearing segments"><div class="ui center aligned segment"><h1 class="ui center aligned icon header"><i class="circular remove red icon"></i><div class="content animated rubberBand">Insufficient authorization</div></h1></div><div class="ui '.$config['forum_color'].' padded segment"><div class="ui icon warning message"><i class="meh icon"></i><div class="content"><div class="header">Oops...</div><p>You do not have <strong>permission</strong> to lock/unlock this topic.</p></div></div>');
// Lorem...
define('ERR_AUTH_EDIT','<center><h1 class="ui center aligned icon header"><i class="circular remove red icon"></i><div class="content animated rubberBand">Insufficient authorization<div class="sub header">Only moderators or administrators can edit this message.</div></div></h1></center><div class="ui icon warning message"><i class="meh icon"></i><div class="content"><div class="header">Oops...</div><p>You do not have <strong>permission</strong> to avoid this message.</p></div></div></div>');
// The topic is locked
define('ERR_TOPIC_VERR','<div class="ui raised clearing segments"><div class="ui center aligned segment"><h1 class="ui center aligned icon header"><i class="circular remove red icon"></i><div class="content">The topic is locked</div></h1></div><div class="ui '.$config['forum_color'].' padded segment"><div class="ui icon warning message"><i class="meh icon"></i><div class="content"><div class="header">Oops...</div><p>You are <strong>not authorized</strong> to perform this action at this time.</p></div></div>');
// You must have an authorization -> Admin
define('ERR_AUTH_ADMIN','<div class="ui main container animated fadeIn"><div class="ui raised clearing segments"><div class="ui center aligned segment"><h1 class="ui center aligned icon header"><i class="circular remove red icon"></i><div class="content animated rubberBand">Insufficient authorization<div class="sub header">Only administrators have access to this page.</div></div></h1></div><div class="ui '.$config['forum_color'].' padded segment"><div class="ui icon warning message"><i class="meh icon"></i><div class="content"><div class="header">Oops...</div><p>You do not have <strong>permission</strong> to access this administration page.</p></div></div>');
// You must have an authorization -> Moderator or Admin
define('ERR_AUTH_MODO','<div class="ui main container animated fadeIn"><div class="ui raised clearing segments"><div class="ui center aligned segment"><h1 class="ui center aligned icon header"><i class="circular remove red icon"></i><div class="content animated rubberBand">Insufficient authorization<div class="sub header">Only moderators or administrators have access to this page.</div></div></h1></div><div class="ui '.$config['forum_color'].' padded segment"><div class="ui icon warning message"><i class="meh icon"></i><div class="content"><div class="header">Oops...</div><p>You do not have <strong>permission</strong> to access this administration page.</p></div></div>');
// Move topic
define('ERR_AUTH_MOVE','<div class="ui main container animated fadeIn"><div class="ui raised clearing segments"><div class="ui center aligned segment"><h1 class="ui center aligned icon header"><i class="circular remove red icon"></i><div class="content animated rubberBand">Insufficient authorization<div class="sub header">Only moderators or administrators have access to this page.</div></div></h1></div><div class="ui '.$config['forum_color'].' padded segment"><div class="ui icon warning message"><i class="meh icon"></i><div class="content"><div class="header">Oops...</div><p>You do not have <strong>permission</strong> to access this administration page.</p></div></div>');
// Anti flood control (soon)
define('ERR_FLOOD','Anti flood control, you can only post all '.$config['temps_flood'].' sec.<div class="ui divider">Please wait a moment and try again.');
// Wrong User for Private messages
define('ERR_WRONG_USER','<div class="ui main container animated fadeIn"><div class="ui raised clearing segments"><div class="ui center aligned segment"><h1 class="ui center aligned icon header"><i class="circular remove red icon"></i><div class="content animated rubberBand">Wrong User<div class="sub header">Smart ass.</div></div></h1></div><div class="ui '.$config['forum_color'].' padded segment"><div class="ui icon warning message"><i class="meh icon"></i><div class="content"><div class="header">Oops...</div><p>You are not the <strong>right user</strong>.</p></div></div>');
// Do not have permission to remove a topic
define('ERR_AUTH_DELETE_TOPIC','<div class="ui raised clearing segments"><div class="ui center aligned segment"><h1 class="ui center aligned icon header"><i class="circular remove red icon"></i><div class="content animated rubberBand">Insufficient authorization</div></h1></div><div class="ui '.$config['forum_color'].' padded segment"><div class="ui icon warning message"><i class="meh icon"></i><div class="content"><div class="header">Oops...</div><p>You do not have <strong>permission</strong> to delete this topic.</p></div></div>');

